import { StyleSheet, Dimensions } from "react-native";

const { width: screenWidth, height: screenHeight } = Dimensions.get("window");

const styles = StyleSheet.create({
	// ---------------- Global ----------------
	container: {
		flex: 1,
		backgroundColor: "#f9f9f9",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 10,
	},

	// ---------------- Buttons ----------------
	button: {
		backgroundColor: "#4CAF50",
		paddingHorizontal: 28,
		paddingVertical: 14,
		borderRadius: 13,
	},
	buttonText: {
		color: "#fff",
		fontSize: 22,
		fontWeight: "600",
	},
	newReservationButton: {
		position: "absolute",
		bottom: 20,
		right: 20,
		backgroundColor: "#007AFF",
		width: 60,
		height: 60,
		borderRadius: 30,
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		elevation: 5,
	},
	nextButton: {
		flex: 1,
		backgroundColor: "#4CAF50",
		paddingVertical: 14,
		borderRadius: 10,
		alignItems: "center",
		maxHeight: 60,
	},
	prevButton: {
		flex: 1,
		backgroundColor: "#FF7043",
		paddingVertical: 14,
		borderRadius: 10,
		alignItems: "center",
	},
	buttonTextSettings: {
		color: "#fff",
		fontWeight: "600",
		fontSize: 17,
		textAlign: "center",
	},
	buttonTextCancel: {
		color: "#fff",
		fontWeight: "600",
		fontSize: 17,
		textAlign: "center",
	},
	buttonRow: {
		flexDirection: "row",
		justifyContent: "space-between", // espace égal entre les boutons
		marginTop: 20,
		gap: 10, // si RN >= 0.70, sinon on peut utiliser margin sur les boutons
	},

	// ---------------- Popup / Modals ----------------
	popupMainWrapper: {
		position: "absolute",
		top: 40,
		left: 0,
		right: 0,
		bottom: 120,
		justifyContent: "center",
		alignItems: "center",
	},
	popupMain: {
		width: screenWidth * 0.91,
		height: screenHeight * 0.7,
		backgroundColor: "#fff",
		borderRadius: 20,
		paddingTop: 0, // ⭐ Aucun padding en haut
		paddingHorizontal: 15,
		paddingBottom: 15,
		shadowColor: "#000",
		shadowOpacity: 0.3,
		shadowOffset: { width: 0, height: 3 },
		shadowRadius: 5,
		elevation: 10,
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.4)",
		justifyContent: "center",
		alignItems: "center",
		padding: 15,
	},
	modalForm: {
		width: "55%",
		maxHeight: "80%",
		backgroundColor: "#fff",
		borderRadius: 12,
		padding: 25,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 8,
	},
	modalTitle: {
		fontSize: 22,
		fontWeight: "700",
		marginBottom: 20,
		textAlign: "center",
	},

	overlaySettings: {
		flex: 1,
		backgroundColor: "rgba(0,0,0,0.5)",
		justifyContent: "center",
		alignItems: "center",
		padding: 20,
	},
	modalSettings: {
		width: 300,
		backgroundColor: "#fff",
		borderRadius: 16,
		paddingVertical: 25,
		paddingHorizontal: 20,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.1,
		shadowRadius: 12,
		elevation: 10,
		alignItems: "center",
	},
	modalTitleSettings: {
		fontSize: 20,
		fontWeight: "700",
		marginBottom: 25,
		textAlign: "center",
		color: "#333",
	},
	modalButtonSettings: {
		backgroundColor: "#4A90E2",
		paddingVertical: 14,
		paddingHorizontal: 25,
		borderRadius: 10,
		marginVertical: 8,
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.1,
		shadowRadius: 6,
	},
	modalButtonCancel: {
		backgroundColor: "#E94B3C",
		paddingVertical: 14,
		paddingHorizontal: 25,
		borderRadius: 10,
		marginVertical: 8,
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
	},

	// ---------------- Text / Labels ----------------
	realTableText: { fontSize: 38, fontWeight: "700", color: "#111" },
	internalText: { fontSize: 23, color: "#666" },
	smallText: { color: "#333", fontSize: 17, marginRight: 8 },
	label: { fontWeight: "700", width: 230, fontSize: 18, color: "#334155" },
	value: { color: "#0F172A", fontSize: 18, flexShrink: 1 },
	hint: { color: "#64748B", marginLeft: 8, fontSize: 14 },

	// ---------------- Cards / List ----------------
	timeSlot: {
		backgroundColor: "#e0e0e0",
		padding: 10,
		marginTop: 10,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		borderRadius: 6,
	},
	timeText: { fontSize: 18, fontWeight: "600" },
	totalText: { fontSize: 14, color: "#666" },
	card: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 10,
		paddingHorizontal: 10,
		backgroundColor: "#fff",
		borderRadius: 4,
		marginVertical: 4,
		position: "relative",
	},
	leftCol: { flex: 1 },
	rightCol: { alignItems: "flex-end" },
	infoText: { fontSize: 16, fontWeight: "600" },
	subText: { fontSize: 13, fontWeight: "500" },
	separator: { height: 1, backgroundColor: "#e0e0e0", marginHorizontal: 10 },
	greenStripe: {
		position: "absolute",
		left: 0,
		top: 0,
		bottom: 0,
		width: 8,
		backgroundColor: "#2E8B57",
		borderTopLeftRadius: 4,
		borderBottomLeftRadius: 4,
		zIndex: 1,
	},
	reservationInfo: {
		fontSize: 15,
		color: "#333",
		fontWeight: "500",
		marginBottom: 2,
	},

	// ---------------- Mini / Add ----------------
	miniWrapper: {
		position: "absolute",
		bottom: 40,
		alignItems: "center",
		justifyContent: "center",
		zIndex: 5,
	},
	popupMini: {
		width: 110,
		height: 110,
		backgroundColor: "#f0f9ff",
		borderRadius: 13,
		marginRight: 16,
		padding: 12,
		justifyContent: "space-between",
		alignItems: "center",
		elevation: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.25,
		shadowRadius: 8,
		borderWidth: 1,
		borderColor: "#e0f2fe",
	},
	miniTitle: {
		fontWeight: "700",
		color: "#0F172A",
		fontSize: 16,
		textAlign: "center",
	},
	miniSub: {
		fontSize: 13,
		color: "#64748B",
		textAlign: "center",
		marginTop: 4,
	},
	miniArrive: {
		fontSize: 12,
		color: "#94A3B8",
		textAlign: "center",
		marginTop: 4,
	},
	addButton: {
		backgroundColor: "#10B981",
		justifyContent: "center",
		alignItems: "center",
		width: 110,
		height: 110,
		borderRadius: 13,
	},
	addText: { color: "black", fontSize: 32, fontWeight: "700" },

	// ---------------- Dropdowns ----------------
	dropdown: {
		backgroundColor: "#fff",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ccc",
	},
	dropdownContainer: {
		backgroundColor: "#fff",
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ccc",
		marginTop: 2,
	},
	simpleDropdown: {
		backgroundColor: "#fff",
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 8,
		marginTop: 4,
	},
	simpleDropdownItem: {
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
	},
	dropdownOptionText: { fontSize: 14, fontWeight: "500" },
	valueButton: {
		paddingVertical: 10,
		paddingHorizontal: 8,
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 8,
	},
	settingsButton: { marginLeft: "auto", padding: 4 },

	headerRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center", // ⭐ Molette alignée avec le texte
		paddingTop: 8,
		paddingBottom: 0, // ⭐ Aucun padding en bas
		paddingHorizontal: 0,
	},
	statusRow: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 4, // ⭐ Espace minimal
		marginBottom: 10,
	},
	badge: {
		paddingHorizontal: 13,
		paddingVertical: 8,
		borderRadius: 15,
		marginRight: 12,
	},
	badgeOccupied: {
		backgroundColor: "#FBBF24",
	},
	badgeText: {
		color: "#fff",
		fontWeight: "600",
		fontSize: 13,
	},
	contentScroll: {
		flex: 1,
		marginTop: 8,
	},
	block: {
		backgroundColor: "#FBFBFD",
		borderRadius: 15,
		padding: 16,
		marginBottom: 10,
	},
	blockTitle: {
		fontSize: 16,
		fontWeight: "600",
		marginBottom: 10,
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
		flexWrap: "wrap",
	},
	separatorHorizontal: {
		height: 1,
		backgroundColor: "#94A3B8",
		marginBottom: 10,
		width: "100%",
	},

	title: {
		fontSize: 20,
		fontWeight: "600",
		marginBottom: 10,
	},

	textFloor: {
		marginTop: 10,
		fontSize: 20,
		color: "black",
		fontWeight: "bold",
		marginHorizontal: 20,
	},

	groupBox: {
		backgroundColor: "white",
		borderRadius: 16,
		paddingVertical: 10,
		paddingHorizontal: 15,
		marginTop: 10,
		width: "100%",
		marginLeft: 10,
		marginRight: 40,
	},

	fakeButtonText: {
		color: "black",
		fontWeight: "400",
		marginLeft: 10,
		fontSize: 20,
	},

	separatorThin: {
		height: 1,
		backgroundColor: "#CBD5E1",
		alignSelf: "center",
		width: "99%",
		marginVertical: 5,
	},
	fakeButton: {
		backgroundColor: "#94A3B8",
		paddingVertical: 10,
		paddingHorizontal: 15,
		borderRadius: 9999,
		marginVertical: 6,
	},
	text: {
		fontSize: 16,
		color: "black",
		textAlign: "center",
	},
	input: {
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 10,
		paddingHorizontal: 12,
		paddingVertical: 10,
		fontSize: 17,
		marginBottom: 12,
		backgroundColor: "#f7f7f7",
	},
	filterButton: {
		paddingVertical: 6,
		paddingHorizontal: 12,
		borderRadius: 6,
		backgroundColor: "#eee",
	},
	activeButton: {
		backgroundColor: "#cce5ff",
	},
	reservationContainer: {
		flexDirection: "row",
		alignItems: "center",
		marginVertical: 5,
		backgroundColor: "#fff",
		borderRadius: 8,
		overflow: "hidden", // pour que la barre ne dépasse pas
		elevation: 2, // ombre android
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.2,
		shadowRadius: 1.41,
	},

	counterButton: {
		width: 32,
		height: 32,
		borderRadius: 8,
		borderWidth: 1,
		borderColor: "#ccc",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f0f0f0",
	},
	productRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginVertical: 4,
	},
	categoryTitle: {
		fontSize: 18,
		fontWeight: "700",
		marginBottom: 8,
	},
	quantityText: {
		marginHorizontal: 8,
		fontSize: 16,
		fontWeight: "500",
	},
	scrollContainer: {
		paddingBottom: 20,
	},

	dropdownButton: {
		padding: 10,
		borderRadius: 8,
		marginBottom: 10,
		borderWidth: 1,
	},
	dropdownButtonText: {
		fontSize: 14,
		fontWeight: "500",
	},

	// ============ DASHBOARD - Filter Buttons ============
	// ============ MORPHING NAV (FILTERS) ============
	morphingNavContainer: {
		marginBottom: 20,
		paddingHorizontal: 10,
	},
	morphingNavInner: {
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		gap: 10,
		flexWrap: "wrap",
		position: "relative",
	},
	morphingNavSlider: {
		position: "absolute",
		height: 48,
		borderRadius: 25,
		borderWidth: 2,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.15,
		shadowRadius: 6,
		elevation: 4,
	},
	morphingNavItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 18,
		borderRadius: 25,
		gap: 8,
		minWidth: 120,
		justifyContent: "center",
		zIndex: 1,
	},
	morphingNavIcon: {
		fontSize: 18,
	},
	morphingNavLabel: {
		fontSize: 14,
		letterSpacing: 0.3,
	},

	// Legacy filter styles (kept for compatibility)
	filterButtonRow: {
		flexDirection: "row",
		marginBottom: 15,
		paddingHorizontal: 10,
		gap: 8,
	},
	filterButtonActives: {
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 10,
		backgroundColor: "#E8F5E9",
		alignItems: "center",
		justifyContent: "center",
		minWidth: 90,
		borderWidth: 2,
		borderColor: "#4CAF50",
	},
	filterButtonActivesActive: {
		backgroundColor: "#4CAF50",
	},
	filterButtonOuverte: {
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 10,
		backgroundColor: "#E3F2FD",
		alignItems: "center",
		justifyContent: "center",
		minWidth: 90,
		borderWidth: 2,
		borderColor: "#2196F3",
	},
	filterButtonOuverteActive: {
		backgroundColor: "#2196F3",
	},
	filterButtonTermine: {
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 10,
		backgroundColor: "#F5F5F5",
		alignItems: "center",
		justifyContent: "center",
		minWidth: 90,
		borderWidth: 2,
		borderColor: "#9E9E9E",
	},
	filterButtonTermineActive: {
		backgroundColor: "#9E9E9E",
	},
	filterButtonAnnulee: {
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 10,
		backgroundColor: "#FFEBEE",
		alignItems: "center",
		justifyContent: "center",
		minWidth: 90,
		borderWidth: 2,
		borderColor: "#F44336",
	},
	filterButtonAnnuleeActive: {
		backgroundColor: "#F44336",
	},
	filterButtonText: {
		color: "#333",
		fontSize: 13,
		fontWeight: "600",
		textAlign: "center",
	},
	filterButtonTextActive: {
		color: "#fff",
		fontSize: 13,
		fontWeight: "700",
		textAlign: "center",
	},

	// ============ RESERVATION CARDS ============
	reservationCardContainer: {
		flexDirection: "column",
		width: "48%",
		borderRadius: 12,
		padding: 10,
		margin: "1%",
		borderWidth: 1.5,
		position: "relative",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	reservationCardHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 12,
		paddingBottom: 10,
		borderBottomWidth: 1,
		borderBottomColor: "rgba(128, 128, 128, 0.2)",
	},
	reservationCardContent: {
		flexDirection: "row",
		flex: 1,
		gap: 10,
	},
	reservationCardLeftCol: {
		flex: 1,
		paddingRight: 6,
	},
	reservationCardRightCol: {
		flex: 1,
		paddingLeft: 6,
		alignItems: "flex-end",
	},
	reservationCardInfoRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
	},
	reservationCardIcon: {
		fontSize: 16,
		marginRight: 8,
	},
	reservationCardInfoText: {
		fontSize: 13,
		fontWeight: "500",
		letterSpacing: 0.1,
	},
	reservationCardName: {
		fontSize: 22,
		fontWeight: "700",
		textTransform: "capitalize",
		letterSpacing: 0.5,
	},
	reservationCardSettingsIcon: {
		fontSize: 26,
		opacity: 0.7,
	},
	reservationCardChairTouchable: {
		marginRight: 8,
	},
	reservationCardStatusDot: {
		width: 10,
		height: 10,
		borderRadius: 5,
		marginRight: 8,
	},
	// Legacy styles (à supprimer si non utilisés ailleurs)
	reservationCardInfoGroup: {
		marginBottom: 12,
	},
	reservationCardTableRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 16,
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 8,
		backgroundColor: "rgba(0, 122, 255, 0.08)",
	},
	reservationCardChairButton: {
		marginRight: 8,
	},
	reservationCardChairIcon: {
		fontSize: 28,
	},
	reservationCardTableNumber: {
		fontSize: 18,
		fontWeight: "700",
		letterSpacing: 0.3,
	},
	reservationCardDetailLabel: {
		fontSize: 13,
		fontWeight: "600",
		marginBottom: 4,
		opacity: 0.7,
		letterSpacing: 0.3,
	},
	reservationCardDetailValue: {
		fontSize: 16,
		fontWeight: "500",
		letterSpacing: 0.2,
	},
	reservationCardStatusBadge: {
		paddingVertical: 6,
		paddingHorizontal: 12,
		borderRadius: 6,
		alignSelf: "flex-end",
		marginTop: 4,
	},
	reservationCardStatusText: {
		fontSize: 13,
		fontWeight: "700",
		letterSpacing: 0.5,
	},
	reservationCardActionIcon: {
		fontSize: 24,
		marginTop: 12,
	},

	// ============ FLOOR PANEL ============
	floorSectionTitle: {
		fontSize: 16,
		fontWeight: "600",
		marginBottom: 10,
		paddingVertical: 8,
		paddingHorizontal: 10,
		borderRadius: 8,
		backgroundColor: "rgba(0, 122, 255, 0.1)",
	},
	floorMenuItemText: {
		fontSize: 14,
		fontWeight: "500",
		paddingVertical: 11,
		paddingHorizontal: 10,
	},
});

export default styles;
